### ISSUE TITLE
generateTextFromHTML contains css

### ISSUE THREAD

**Issue by zoellner** [nodemailer/nodemailer#258]
I am using generateTextFromHTML: true but the created text email still contains css code. 

I am using email boilerplate with a few modifications, it starts with the following code

``` Jade
doctype html
html(xmlns='http://www.w3.org/1999/xhtml')
if (!campaign)
  - campaign = ''
head
    meta(http-equiv='Content-Type', content='text/html; charset=utf-8')
    meta(name='viewport', content='width=device-width, initial-scale=1.0')
    block title
    style(type='text/css').
      /* Based on The MailChimp Reset INLINE: Yes. */
      /* Client-specific Styles */
      #outlook a {padding:0;} /* Force Outlook to provide a "view in browser" menu link. */
      body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;}
      /* Prevent Webkit and Windows Mobile platforms from changing default font sizes.*/
      .ExternalClass {width:100%;} /* Force Hotmail to display emails at full width */
      .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}
      /* Forces Hotmail to display normal line spacing.  More on that: http://www.emailonacid.com/forum/viewthread/43/ */
      #backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}
```

The text portion of the email starts as follows:

``` css
.ExternalClass { width: 100%; } .ExternalClass, .ExternalClass p, .=
ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass =
div { line-height: 100%; } body { -webkit-text-size-adjust: none; =
-ms-text-size-adjust: none; margin: 0; padding: 0; } table td { =
border-collapse: collapse; } h1, h2, h3, h4, h5, h6, p { color: black; =
line-height: 1.2em; margin: 0; padding: 0; } body { background: #EFEFEF; =
min-height: 1000px; color: #000000; font-family: Arial, Helvetica, =
sans-serif; font-family: Arial, Helvetica, sans-serif; font-size: 16px; =
line-height: 1.4em; } span.yshortcuts { color: #000000; background: =
transparent; border: none; } span.yshortcuts:hover, span.yshortcuts:active,=
 span.yshortcuts:focus { color: #000000; background: transparent; border: =
none; } XHTML-STRIPONREPLY { display: none; } a[href^=3D=22tel=22], =
a[href^=3D=22sms=22] { text-decoration: none; pointer-events: none; cursor:=
 default; } .mobile=5Flink a[href^=3D=22tel=22], .mobile=5Flink =
a[href^=3D=22sms=22] { text-decoration: none; pointer-events: auto; cursor:=
 default; } p, a[href^=3D=22tel=22], a[href^=3D=22sms=22] { color: #000000;=
 } a, a:link { color: #007DC3; text-decoration: none; } a:visited { color: =
#005482; text-decoration: none; } a:focus { color: #005482; =
text-decoration: underline; } a:hover { color: #005482; text-decoration: =
underline; } .mobile=5Flink a[href^=3D=22tel=22], .mobile=5Flink =
a[href^=3D=22sms=22] { color: #007DC3 !important; } #cv-poweredBy { =
text-align: center; margin: 10px; padding: 10px; } @media screen and =
(max-width: 580px) { *[class].contents .column { width: 100% !important; } =
*[class].gradExpertsFooter .column { width: 100% !important; } } @media =
screen and (max-width: 480px) { *[class].interests .column { width: 100% !=
important; } *[class].interests .column td { text-align: left !important; }=
 *[class].interests .column td .break { display: inline !important; } =
*[class].eventFooter img { width: 26px !important; height: 52px !important;=
 } *[class].eventFooter span { display: block !important; } } @media screen=
 and (max-width: 360px) { *[class].gradExpertsFooter .share { display: none=
 !important; } } Email Verification
```
